kind: pipeline
name: default

steps:
  - name: publish to gcr
    image: plugins/gcr
    settings:
      repo: gcr.io/k8s-0529/ubuntu
      tags: v1
      json_key:
        from_secret: google_credentials