kind: pipeline
type: docker
name: default

steps:
- name: publish to gcr
  image: plugins/gcr
  settings:
    repo: gcr.io/k8s-0529/ubuntu
    tags: v1
    json_key:
      from_secret: google_credentials
## 載入 docker config 設定
image_pull_secrets:
  - dockerconfigjson
# 觸發 pipeline 條件
trigger:
  ref:
    include: [refs/heads/develop, refs/heads/qatest, refs/heads/int, refs/tags/v*, refs/tags/t*, refs/tags/release-v*]